# Generated by Django 3.2.2 on 2021-05-17 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=30)),
                ('comment', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 17, 18, 45, 47, 868599, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('images', models.TextField(blank=True, max_length=500, null=True)),
                ('components', models.TextField(blank=True, max_length=500, null=True)),
                ('state', models.IntegerField(default=0)),
                ('author', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 17, 18, 45, 47, 869217, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 5, 17, 18, 45, 47, 869245, tzinfo=utc))),
            ],
        ),
    ]
